### ISSUE TITLE
질문드립니다.

### ISSUE THREAD

**Issue by Lay4U** [coreanq/kw_condition#4]
```
pywintypes.com_error: (-2147352567, '예외가 발생했습니다.', (0, 'Microsoft Excel', "파일 형식 또는 파일 확장명이 잘못되 어 'chegyeol.xlsx' 파일을 열 수 없습니다. 파일이 손상되지 않았는지, 파일 확장명이 파일 형식과 일치하는지 확인하십시오.", 'xlmain11.chm', 0, -2146827284), None)
```
체결 정보 엑셀 생성으로 하면 이렇게 나오네요

분할 매수와 익절 손절 기능 없이 조건검색 만족시 한번에 100만원어치를 사고 싶습니다. 어떻게 해야할까요?

**Comment by Lay4U** [comment]
```
Traceback (most recent call last):
  File "main.py", line 1745, in _OnReceiveChejanData
    self.makeChegyeolInfo(jongmok_code, fidList)
  File "main.py", line 1878, in makeChegyeolInfo
    self.calculateSuik(jongmok_code, current_price)
  File "main.py", line 1328, in calculateSuik
    current_jango = self.jangoInfo[jongmok_code]
KeyError: '035810'
```

오늘 모의투자로 테스트하다가 이런 에러가 나왔네요

코드는 다음과 같습니다.

https://gist.github.com/Lay4U/2e0702b024c232c911356e06f0760abe

2) 매수 주문 접수와 익절 손절 기능이 어디에 있는지 정확히 모르겠네요 혹시 알려주실수 있으신가요?

**Comment by Lay4U** [comment]
![image](https://user-images.githubusercontent.com/31833270/83832409-8fb6bb00-a724-11ea-927c-19a08fd6ffca.png)

HTS로는 실시간 2개 켜져있는 상태이고 `sendCondition`으로 감시하고 있는 조건식은 1개인데 이런 오류가 뜨네요 ㅠ `TR_TIME_LIMIT_MS = 7600` 두배로 설정했습니다.

**Comment by coreanq** [comment]
하도 이쪽을 안보고  해서 답변이 늦었네요 
1. 엑셀저장 기능은 안되네요 (수정예정) , 매수/익절/손절 2, 2-1 답변 참고 
2. 매수 주문의 경우 DeterminebuyStateEntered 함수 내에 여러 조건을 판단한후 SendOrder 하는 부분이 있습니다. 
2-1 익절 손절의 경우 체결 정보를 받은 뒤에 수행하며, ProcessStoploss 함수내에 존재 합니다. 
3. 실시간 조건이 30개를 초과했다는 것은 제 생각에 sendCondtion 이 여러번 수행되서 그러는게 아닌가 싶습니다.
