### ISSUE TITLE
kiwoom_charles_auth.json

### ISSUE THREAD

**Issue by privateKan** [coreanq/kw_condition#5]
kiwoom_charles_auth.json 양식 예제를 보고싶습니다 어떻게 구할수있을까요?

**Comment by coreanq** [comment]
자신의 구글 드라이브 인증 키로 
아래 사이트 참고 하시면 됩니다
http://hleecaster.com/python-google-drive-spreadsheet-api/

**Comment by privateKan** [comment]
감사합니다.
구글인증키양식인가요?

**Comment by coreanq** [comment]
네

**Comment by privateKan** [comment]
프로그램 실행시 텍스트창과 실행이란 버튼이있는데 그 텍스트창에는 뭐가들어가는지.... 알수있을까요..?

**Comment by coreanq** [comment]
python eval() 기능하던건데 지금은 주석처리 되었고 그냥 테스트용입니다

**Comment by privateKan** [comment]
아 좋은정보,자료 정말감사합니다.
