### ISSUE TITLE
로그인시 에러가나옵니다...

### ISSUE THREAD

**Issue by privateKan** [coreanq/kw_condition#6]
requestOpw00018 8147671911 commRqData() 요청 전문 작성 실패 (-202)  라고 뜨는데 이유가무엇인지 알수있을까요..?

**Comment by coreanq** [comment]
답변이 늦었네요 너무 상황 설명이 안되있어서 답변 드리기가 힘드네요
실제 계좌는 있으신건지?
모의 투자 계좌로 접속 한건 아니신지?
실제 계좌로 접속하기 위한 자동 로그인 설정 및 계좌 번호 저장은 하셨는지? 
등등 많네요

**Comment by privateKan** [comment]
아... 가상계좌는 안되나봐요?

**Comment by coreanq** [comment]
처음 접속 하시는 거면 첫 접속이 모의투자 계정으로 이뤄져서 
우선 모의투자 키움증권 사이트에서 신청하시고 하시고 그 뒤 상황좀 다시 말씀해주세요
