### ISSUE TITLE
Could not convert to integer: 3221226525. Path 'exitCode'.

### ISSUE THREAD

**Issue by hola-ai** [coreanq/kw_condition#7]
프로그램이 자꾸 종료되어서 Visual Studio 로 실행했더니
한 20분 정도 돌다가 아래와 같이 나오고 멈춥니다.

+12:58:41.474904 롯데정보통신
+13:01:03.841801 비피도
* 13:01:31.034358 makeJangoInfoFile
종목이름:쇼박스, 기본손절:2928.32
종목이름:토니모리, 기본손절:9844.58
종목이름:비피도, 기본손절:19405.86
-13:02:12.496349 비피도
Press any key to continue . . .

그리고 키를 누르면 종료되면서 첨부와 같은 메세지 창이 뜹니다.
![kw_condition_error](https://user-images.githubusercontent.com/8622121/99785661-c8c2da80-2b60-11eb-9a50-fb166b6296e6.png)

모의투자 입니다.

**Comment by coreanq** [comment]
메모리 릭 문제가 있었는데 수정 했는데 최신버전으로 다시 확인해보시겠어요?
